# Generated by Django 4.2.7 on 2023-11-28 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accountapp", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="HelloWorld",),
    ]
