# Generated by Django 4.2.7 on 2023-11-24 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commentapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment", old_name="create_at", new_name="created_at",
        ),
    ]
